# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      # Prometheus will scrape the metrics that the OTel Collector has processed and exposed
      - targets: ["otel-collector:8889"]
